// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbF8ENeJMHKwRk5CzVfjVpAniwrqkrvjE',
    appId: '1:526154473270:web:4d420161bdaed42e2add97',
    messagingSenderId: '526154473270',
    projectId: 'mental-mana',
    authDomain: 'mental-mana.firebaseapp.com',
    storageBucket: 'mental-mana.firebasestorage.app',
    measurementId: 'G-FV0ZG1W40T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfLYkZlr6sD1c5nDdEAZReQXcf2dNAww',
    appId: '1:526154473270:android:c7abebca595dad272add97',
    messagingSenderId: '526154473270',
    projectId: 'mental-mana',
    storageBucket: 'mental-mana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4VrtjejsqvNUw9vf8PFSQ7_sCQ_ChFQ',
    appId: '1:526154473270:ios:5abe7f7a9470806e2add97',
    messagingSenderId: '526154473270',
    projectId: 'mental-mana',
    storageBucket: 'mental-mana.firebasestorage.app',
    iosBundleId: 'com.example.mentalAssistanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq4VrtjejsqvNUw9vf8PFSQ7_sCQ_ChFQ',
    appId: '1:526154473270:ios:5abe7f7a9470806e2add97',
    messagingSenderId: '526154473270',
    projectId: 'mental-mana',
    storageBucket: 'mental-mana.firebasestorage.app',
    iosBundleId: 'com.example.mentalAssistanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbF8ENeJMHKwRk5CzVfjVpAniwrqkrvjE',
    appId: '1:526154473270:web:80d0cc56493b072c2add97',
    messagingSenderId: '526154473270',
    projectId: 'mental-mana',
    authDomain: 'mental-mana.firebaseapp.com',
    storageBucket: 'mental-mana.firebasestorage.app',
    measurementId: 'G-JKBTTM19V1',
  );
}
